name: Copy Specific HTML Files

on:
  push:
    paths:
      - 'org/html/**' # Trigger the workflow when files in org/html/ change

jobs:
  copy-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy specific HTML files
      run: |
        # Define the list of HTML files to copy
        files_to_copy=(
          "org/html/index.html"
          "org/html/PythonSetup.html"
          "org/html/PythonBasics.html"
          "org/html/PythonIntermediateSkills.html"
          "org/html/ClassicalInfoQuantumInfo.html"
          "org/html/Operators.html"
          "org/html/AppendixQiskitIBMSimRun.html"
          "org/html/AppendixExBellCircuits.html"
          "org/html/nbgrader.html"
        )

        # Ensure the docs directory exists
        mkdir -p docs

        # Copy each file from the list to the docs/ directory
        for file in "${files_to_copy[@]}"; do
          if [ -f "$file" ]; then
            cp "$file" docs/
          else
            echo "Warning: $file does not exist, skipping."
          fi
        done

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs/
        git commit -m "Copy specific HTML files from org/html to docs"  || echo "No changes to commit"

        # Ensure we are up to date before pushing
        git pull --rebase origin main
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List files in docs
      run: ls -l docs

